// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MAEMS.Infrastructure.Models;

public partial class AdmissionType
{
    public int AdmissionTypeId { get; set; }

    public string AdmissionTypeName { get; set; }

    public int? EnrollmentYearId { get; set; }

    public string Type { get; set; }

    public string RequiredDocumentList { get; set; }
    public string? EligibilityRules { get; set; }
    public string? PriorityRules { get; set; }
    public bool? IsActive { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual EnrollmentYear EnrollmentYear { get; set; }

    public virtual ICollection<ProgramAdmissionConfig> ProgramAdmissionConfigs { get; set; } = new List<ProgramAdmissionConfig>();
}