// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MAEMS.Infrastructure.Models;

public partial class AgentLog
{
    public int LogId { get; set; }

    public int? ApplicationId { get; set; }

    public int? DocumentId { get; set; }

    public string AgentType { get; set; }

    public string Action { get; set; }

    public string Status { get; set; }

    public string OutputData { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual Application Application { get; set; }

    public virtual Document Document { get; set; }
}