// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MAEMS.Infrastructure.Models;

public partial class Application
{
    public int ApplicationId { get; set; }

    public int? ApplicantId { get; set; }

    public int? ProgramId { get; set; }

    public int? EnrollmentYearId { get; set; }

    public int? CampusId { get; set; }

    public int? AdmissionTypeId { get; set; }

    public string Status { get; set; }

    public DateTime? SubmittedAt { get; set; }

    public DateTime? LastUpdated { get; set; }

    public int? AssignedOfficerId { get; set; }

    public string Notes { get; set; }

    public bool? RequiresReview { get; set; }

    public virtual AdmissionType AdmissionType { get; set; }

    public virtual ICollection<AgentLog> AgentLogs { get; set; } = new List<AgentLog>();

    public virtual Applicant Applicant { get; set; }

    public virtual User AssignedOfficer { get; set; }

    public virtual Campus Campus { get; set; }

    public virtual ICollection<Document> Documents { get; set; } = new List<Document>();

    public virtual EnrollmentYear EnrollmentYear { get; set; }

    public virtual ICollection<Payment> Payments { get; set; } = new List<Payment>();

    public virtual Program Program { get; set; }
}