// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MAEMS.Infrastructure.Models;

public partial class Application
{
    public int ApplicationId { get; set; }

    public int? ApplicantId { get; set; }

    public string Status { get; set; }

    public DateTime? SubmittedAt { get; set; }

    public DateTime? LastUpdated { get; set; }

    public int? AssignedOfficerId { get; set; }

    public int? ConfigId { get; set; }

    public string Notes { get; set; }

    public bool? RequiresReview { get; set; }
    
    public string Level { get; set; }

    public virtual ICollection<AgentLog> AgentLogs { get; set; } = new List<AgentLog>();

    public virtual Applicant Applicant { get; set; }

    public virtual User AssignedOfficer { get; set; }

    public virtual ProgramAdmissionConfig Config { get; set; }

    public virtual ICollection<Payment> Payments { get; set; } = new List<Payment>();
}