// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MAEMS.Infrastructure.Models;

public partial class Article
{
    public int ArticleId { get; set; }

    public string Title { get; set; }

    public string Content { get; set; }

    public string Thumbnail { get; set; }

    public int? AuthorId { get; set; }

    public string Status { get; set; }
    
    public bool? IsRegisterable { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual User Author { get; set; }

    public virtual ICollection<RegisterEvent> RegisterEvents { get; set; } = new List<RegisterEvent>();
}