// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MAEMS.Infrastructure.Models;

public partial class Campus
{
    public int CampusId { get; set; }

    public string Name { get; set; }

    public string Address { get; set; }

    public string Email { get; set; }

    public string PhoneNumber { get; set; }

    public string Description { get; set; }

    public bool? IsActive { get; set; }

    public virtual ICollection<ProgramAdmissionConfig> ProgramAdmissionConfigs { get; set; } = new List<ProgramAdmissionConfig>();
}