// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MAEMS.Infrastructure.Models;

public partial class Document
{
    public int DocumentId { get; set; }

    public int? ApplicationId { get; set; }

    public string DocumentType { get; set; }

    public string FilePath { get; set; }

    public DateTime? UploadedAt { get; set; }

    public string FileName { get; set; }

    public string FileFormat { get; set; }

    public string VerificationResult { get; set; }

    public string VerificationDetails { get; set; }

    public virtual ICollection<AgentLog> AgentLogs { get; set; } = new List<AgentLog>();

    public virtual Application Application { get; set; }
}