// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MAEMS.Infrastructure.Models;

public partial class EnrollmentYear
{
    public int EnrollmentYearId { get; set; }

    public string Year { get; set; }

    public DateOnly? RegistrationStartDate { get; set; }

    public DateOnly? RegistrationEndDate { get; set; }

    public string Status { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual ICollection<AdmissionType> AdmissionTypes { get; set; } = new List<AdmissionType>();

    public virtual ICollection<Program> Programs { get; set; } = new List<Program>();
}