// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MAEMS.Infrastructure.Models;

public partial class LlmChatLog
{
    public int ChatId { get; set; }

    public int? UserId { get; set; }

    public string UserQuery { get; set; }

    public string Message { get; set; }

    public string LlmResponse { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual User User { get; set; }
}