// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MAEMS.Infrastructure.Models;

public partial class Notification
{
    public int NotificationId { get; set; }

    public int? RecipientUserId { get; set; }

    public string NotificationType { get; set; }

    public string Message { get; set; }

    public bool? IsRead { get; set; }

    public DateTime? SentAt { get; set; }

    public virtual User RecipientUser { get; set; }
}