// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MAEMS.Infrastructure.Models;

public partial class Payment
{
    public int PaymentId { get; set; }

    public int? ApplicationId { get; set; }

    public int? ApplicantId { get; set; }

    public decimal? Amount { get; set; }

    public string PaymentMethod { get; set; }

    public string TransactionId { get; set; }

    public string PaymentStatus { get; set; }

    public DateTime? PaidAt { get; set; }

    public string? ReferenceCode { get; set; }

    public virtual Applicant Applicant { get; set; }

    public virtual Application Application { get; set; }
}