// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace MAEMS.Infrastructure.Models;

public partial class postgresContext : DbContext
{
    public postgresContext(DbContextOptions<postgresContext> options)
        : base(options)
    {
    }

    public virtual DbSet<AdmissionType> AdmissionTypes { get; set; }

    public virtual DbSet<AgentLog> AgentLogs { get; set; }

    public virtual DbSet<Applicant> Applicants { get; set; }

    public virtual DbSet<Application> Applications { get; set; }

    public virtual DbSet<Article> Articles { get; set; }

    public virtual DbSet<Campus> Campuses { get; set; }

    public virtual DbSet<Document> Documents { get; set; }

    public virtual DbSet<EnrollmentYear> EnrollmentYears { get; set; }

    public virtual DbSet<LlmChatLog> LlmChatLogs { get; set; }

    public virtual DbSet<Major> Majors { get; set; }

    public virtual DbSet<Notification> Notifications { get; set; }

    public virtual DbSet<Payment> Payments { get; set; }

    public virtual DbSet<Program> Programs { get; set; }

    public virtual DbSet<ProgramAdmissionConfig> ProgramAdmissionConfigs { get; set; }

    public virtual DbSet<Role> Roles { get; set; }

    public virtual DbSet<User> Users { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder
            .HasPostgresEnum("auth", "aal_level", new[] { "aal1", "aal2", "aal3" })
            .HasPostgresEnum("auth", "code_challenge_method", new[] { "s256", "plain" })
            .HasPostgresEnum("auth", "factor_status", new[] { "unverified", "verified" })
            .HasPostgresEnum("auth", "factor_type", new[] { "totp", "webauthn", "phone" })
            .HasPostgresEnum("auth", "oauth_authorization_status", new[] { "pending", "approved", "denied", "expired" })
            .HasPostgresEnum("auth", "oauth_client_type", new[] { "public", "confidential" })
            .HasPostgresEnum("auth", "oauth_registration_type", new[] { "dynamic", "manual" })
            .HasPostgresEnum("auth", "oauth_response_type", new[] { "code" })
            .HasPostgresEnum("auth", "one_time_token_type", new[] { "confirmation_token", "reauthentication_token", "recovery_token", "email_change_token_new", "email_change_token_current", "phone_change_token" })
            .HasPostgresEnum("realtime", "action", new[] { "INSERT", "UPDATE", "DELETE", "TRUNCATE", "ERROR" })
            .HasPostgresEnum("realtime", "equality_op", new[] { "eq", "neq", "lt", "lte", "gt", "gte", "in" })
            .HasPostgresEnum("storage", "buckettype", new[] { "STANDARD", "ANALYTICS", "VECTOR" })
            .HasPostgresExtension("extensions", "pg_stat_statements")
            .HasPostgresExtension("extensions", "pgcrypto")
            .HasPostgresExtension("extensions", "uuid-ossp")
            .HasPostgresExtension("graphql", "pg_graphql")
            .HasPostgresExtension("vault", "supabase_vault");

        modelBuilder.Entity<AdmissionType>(entity =>
        {
            entity.HasKey(e => e.AdmissionTypeId).HasName("admission_type_pkey");

            entity.ToTable("admission_type");

            entity.Property(e => e.AdmissionTypeId).HasColumnName("admission_type_id");
            entity.Property(e => e.AdmissionTypeName)
                .HasMaxLength(255)
                .HasColumnName("admission_type_name");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("timestamp without time zone")
                .HasColumnName("created_at");
            entity.Property(e => e.EnrollmentYearId).HasColumnName("enrollment_year_id");
            entity.Property(e => e.IsActive)
                .HasDefaultValue(true)
                .HasColumnName("is_active");
            entity.Property(e => e.RequiredDocumentList)
                .HasColumnType("jsonb")
                .HasColumnName("required_document_list");
            entity.Property(e => e.Type)
                .HasMaxLength(50)
                .HasColumnName("type");

            entity.HasOne(d => d.EnrollmentYear).WithMany(p => p.AdmissionTypes)
                .HasForeignKey(d => d.EnrollmentYearId)
                .HasConstraintName("admission_type_enrollment_year_id_fkey");
        });

        modelBuilder.Entity<AgentLog>(entity =>
        {
            entity.HasKey(e => e.LogId).HasName("agent_log_pkey");

            entity.ToTable("agent_log");

            entity.Property(e => e.LogId).HasColumnName("log_id");
            entity.Property(e => e.Action)
                .HasMaxLength(255)
                .HasColumnName("action");
            entity.Property(e => e.AgentType)
                .HasMaxLength(100)
                .HasColumnName("agent_type");
            entity.Property(e => e.ApplicationId).HasColumnName("application_id");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("timestamp without time zone")
                .HasColumnName("created_at");
            entity.Property(e => e.DocumentId).HasColumnName("document_id");
            entity.Property(e => e.OutputData)
                .HasColumnType("jsonb")
                .HasColumnName("output_data");
            entity.Property(e => e.Status)
                .HasMaxLength(50)
                .HasColumnName("status");

            entity.HasOne(d => d.Application).WithMany(p => p.AgentLogs)
                .HasForeignKey(d => d.ApplicationId)
                .HasConstraintName("agent_log_application_id_fkey");

            entity.HasOne(d => d.Document).WithMany(p => p.AgentLogs)
                .HasForeignKey(d => d.DocumentId)
                .HasConstraintName("agent_log_document_id_fkey");
        });

        modelBuilder.Entity<Applicant>(entity =>
        {
            entity.HasKey(e => e.ApplicantId).HasName("applicant_pkey");

            entity.ToTable("applicant");

            entity.HasIndex(e => e.IdIssueNumber, "applicant_id_issue_number_key").IsUnique();

            entity.Property(e => e.ApplicantId).HasColumnName("applicant_id");
            entity.Property(e => e.AllowShare)
                .HasDefaultValue(false)
                .HasColumnName("allow_share");
            entity.Property(e => e.ContactAddress)
                .HasMaxLength(255)
                .HasColumnName("contact_address");
            entity.Property(e => e.ContactEmail)
                .HasMaxLength(150)
                .HasColumnName("contact_email");
            entity.Property(e => e.ContactName)
                .HasMaxLength(255)
                .HasColumnName("contact_name");
            entity.Property(e => e.ContactPhone)
                .HasMaxLength(50)
                .HasColumnName("contact_phone");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("timestamp without time zone")
                .HasColumnName("created_at");
            entity.Property(e => e.DateOfBirth).HasColumnName("date_of_birth");
            entity.Property(e => e.FullName)
                .HasMaxLength(255)
                .HasColumnName("full_name");
            entity.Property(e => e.Gender)
                .HasMaxLength(20)
                .HasColumnName("gender");
            entity.Property(e => e.GraduationYear).HasColumnName("graduation_year");
            entity.Property(e => e.HighSchoolDistrict)
                .HasMaxLength(255)
                .HasColumnName("high_school_district");
            entity.Property(e => e.HighSchoolName)
                .HasMaxLength(255)
                .HasColumnName("high_school_name");
            entity.Property(e => e.HighSchoolProvince)
                .HasMaxLength(255)
                .HasColumnName("high_school_province");
            entity.Property(e => e.IdIssueDate).HasColumnName("id_issue_date");
            entity.Property(e => e.IdIssueNumber)
                .HasMaxLength(50)
                .HasColumnName("id_issue_number");
            entity.Property(e => e.IdIssuePlace)
                .HasMaxLength(255)
                .HasColumnName("id_issue_place");
            entity.Property(e => e.UserId).HasColumnName("user_id");

            entity.HasOne(d => d.User).WithMany(p => p.Applicants)
                .HasForeignKey(d => d.UserId)
                .HasConstraintName("applicant_user_id_fkey");
        });

        modelBuilder.Entity<Application>(entity =>
        {
            entity.HasKey(e => e.ApplicationId).HasName("application_pkey");

            entity.ToTable("application");

            entity.Property(e => e.ApplicationId).HasColumnName("application_id");
            entity.Property(e => e.ApplicantId).HasColumnName("applicant_id");
            entity.Property(e => e.AssignedOfficerId).HasColumnName("assigned_officer_id");
            entity.Property(e => e.ConfigId).HasColumnName("config_id");
            entity.Property(e => e.LastUpdated)
                .HasColumnType("timestamp without time zone")
                .HasColumnName("last_updated");
            entity.Property(e => e.Notes).HasColumnName("notes");
            entity.Property(e => e.RequiresReview)
                .HasDefaultValue(false)
                .HasColumnName("requires_review");
            entity.Property(e => e.Status)
                .HasMaxLength(50)
                .HasColumnName("status");
            entity.Property(e => e.SubmittedAt)
                .HasColumnType("timestamp without time zone")
                .HasColumnName("submitted_at");

            entity.HasOne(d => d.Applicant).WithMany(p => p.Applications)
                .HasForeignKey(d => d.ApplicantId)
                .HasConstraintName("application_applicant_id_fkey");

            entity.HasOne(d => d.AssignedOfficer).WithMany(p => p.Applications)
                .HasForeignKey(d => d.AssignedOfficerId)
                .HasConstraintName("application_assigned_officer_id_fkey");

            entity.HasOne(d => d.Config).WithMany(p => p.Applications)
                .HasForeignKey(d => d.ConfigId)
                .HasConstraintName("application_config_id_fkey");
        });

        modelBuilder.Entity<Article>(entity =>
        {
            entity.HasKey(e => e.ArticleId).HasName("article_pkey");

            entity.ToTable("article");

            entity.Property(e => e.ArticleId).HasColumnName("article_id");
            entity.Property(e => e.AuthorId).HasColumnName("author_id");
            entity.Property(e => e.Content).HasColumnName("content");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("timestamp without time zone")
                .HasColumnName("created_at");
            entity.Property(e => e.Status)
                .HasMaxLength(50)
                .HasColumnName("status");
            entity.Property(e => e.Thumbnail).HasColumnName("thumbnail");
            entity.Property(e => e.Title)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("title");
            entity.Property(e => e.UpdatedAt)
                .HasColumnType("timestamp without time zone")
                .HasColumnName("updated_at");

            entity.HasOne(d => d.Author).WithMany(p => p.Articles)
                .HasForeignKey(d => d.AuthorId)
                .HasConstraintName("article_author_id_fkey");
        });

        modelBuilder.Entity<Campus>(entity =>
        {
            entity.HasKey(e => e.CampusId).HasName("campus_pkey");

            entity.ToTable("campus");

            entity.Property(e => e.CampusId).HasColumnName("campus_id");
            entity.Property(e => e.Address)
                .HasMaxLength(255)
                .HasColumnName("address");
            entity.Property(e => e.Email)
                .HasMaxLength(150)
                .HasColumnName("email");
            entity.Property(e => e.PhoneNumber)
                .HasMaxLength(50)
                .HasColumnName("phone_number");
            entity.Property(e => e.Description).HasColumnName("description");
            entity.Property(e => e.IsActive)
                .HasDefaultValue(true)
                .HasColumnName("is_active");
            entity.Property(e => e.Name)
                .HasMaxLength(255)
                .HasColumnName("name");
        });

        modelBuilder.Entity<Document>(entity =>
        {
            entity.HasKey(e => e.DocumentId).HasName("document_pkey");

            entity.ToTable("document");

            entity.Property(e => e.DocumentId).HasColumnName("document_id");
            entity.Property(e => e.ApplicantId).HasColumnName("applicant_id");
            entity.Property(e => e.DocumentType)
                .HasMaxLength(50)
                .HasColumnName("document_type");
            entity.Property(e => e.FileFormat)
                .HasMaxLength(50)
                .HasColumnName("file_format");
            entity.Property(e => e.FileName)
                .HasMaxLength(255)
                .HasColumnName("file_name");
            entity.Property(e => e.FilePath).HasColumnName("file_path");
            entity.Property(e => e.UploadedAt)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("timestamp without time zone")
                .HasColumnName("uploaded_at");
            entity.Property(e => e.VerificationDetails).HasColumnName("verification_details");
            entity.Property(e => e.VerificationResult)
                .HasMaxLength(50)
                .HasColumnName("verification_result");

            entity.HasOne(d => d.Applicant).WithMany(p => p.Documents)
                .HasForeignKey(d => d.ApplicantId)
                .HasConstraintName("document_applicant_id_fkey");
        });

        modelBuilder.Entity<EnrollmentYear>(entity =>
        {
            entity.HasKey(e => e.EnrollmentYearId).HasName("enrollment_year_pkey");

            entity.ToTable("enrollment_year");

            entity.Property(e => e.EnrollmentYearId).HasColumnName("enrollment_year_id");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("timestamp without time zone")
                .HasColumnName("created_at");
            entity.Property(e => e.RegistrationEndDate).HasColumnName("registration_end_date");
            entity.Property(e => e.RegistrationStartDate).HasColumnName("registration_start_date");
            entity.Property(e => e.Status)
                .HasMaxLength(50)
                .HasColumnName("status");
            entity.Property(e => e.Year)
                .HasMaxLength(20)
                .HasColumnName("year");
        });

        modelBuilder.Entity<LlmChatLog>(entity =>
        {
            entity.HasKey(e => e.ChatId).HasName("llm_chat_log_pkey");

            entity.ToTable("llm_chat_log");

            entity.Property(e => e.ChatId).HasColumnName("chat_id");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("timestamp without time zone")
                .HasColumnName("created_at");
            entity.Property(e => e.LlmResponse).HasColumnName("llm_response");
            entity.Property(e => e.Message).HasColumnName("message");
            entity.Property(e => e.UserId).HasColumnName("user_id");
            entity.Property(e => e.UserQuery).HasColumnName("user_query");

            entity.HasOne(d => d.User).WithMany(p => p.LlmChatLogs)
                .HasForeignKey(d => d.UserId)
                .HasConstraintName("llm_chat_log_user_id_fkey");
        });

        modelBuilder.Entity<Major>(entity =>
        {
            entity.HasKey(e => e.MajorId).HasName("major_pkey");

            entity.ToTable("major");

            entity.HasIndex(e => e.MajorCode, "major_major_code_key").IsUnique();

            entity.Property(e => e.MajorId).HasColumnName("major_id");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("timestamp without time zone")
                .HasColumnName("created_at");
            entity.Property(e => e.Description).HasColumnName("description");
            entity.Property(e => e.IsActive)
                .HasDefaultValue(true)
                .HasColumnName("is_active");
            entity.Property(e => e.MajorCode)
                .HasMaxLength(50)
                .HasColumnName("major_code");
            entity.Property(e => e.MajorName)
                .HasMaxLength(255)
                .HasColumnName("major_name");
        });

        modelBuilder.Entity<Notification>(entity =>
        {
            entity.HasKey(e => e.NotificationId).HasName("notification_pkey");

            entity.ToTable("notification");

            entity.Property(e => e.NotificationId).HasColumnName("notification_id");
            entity.Property(e => e.IsRead)
                .HasDefaultValue(false)
                .HasColumnName("is_read");
            entity.Property(e => e.Message).HasColumnName("message");
            entity.Property(e => e.NotificationType)
                .HasMaxLength(50)
                .HasColumnName("notification_type");
            entity.Property(e => e.RecipientUserId).HasColumnName("recipient_user_id");
            entity.Property(e => e.SentAt)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("timestamp without time zone")
                .HasColumnName("sent_at");

            entity.HasOne(d => d.RecipientUser).WithMany(p => p.Notifications)
                .HasForeignKey(d => d.RecipientUserId)
                .HasConstraintName("notification_recipient_user_id_fkey");
        });

        modelBuilder.Entity<Payment>(entity =>
        {
            entity.HasKey(e => e.PaymentId).HasName("payment_pkey");

            entity.ToTable("payment");

            entity.Property(e => e.PaymentId).HasColumnName("payment_id");
            entity.Property(e => e.Amount)
                .HasPrecision(12, 2)
                .HasColumnName("amount");
            entity.Property(e => e.ApplicantId).HasColumnName("applicant_id");
            entity.Property(e => e.ApplicationId).HasColumnName("application_id");
            entity.Property(e => e.PaidAt)
                .HasColumnType("timestamp without time zone")
                .HasColumnName("paid_at");
            entity.Property(e => e.PaymentMethod)
                .HasMaxLength(100)
                .HasColumnName("payment_method");
            entity.Property(e => e.PaymentStatus)
                .HasMaxLength(50)
                .HasColumnName("payment_status");
            entity.Property(e => e.TransactionId)
                .HasMaxLength(255)
                .HasColumnName("transaction_id");
            entity.Property(e => e.ReferenceCode)
                .HasMaxLength(255)
                .HasColumnName("reference_code");

            entity.HasOne(d => d.Applicant).WithMany(p => p.Payments)
                .HasForeignKey(d => d.ApplicantId)
                .HasConstraintName("payment_applicant_id_fkey");

            entity.HasOne(d => d.Application).WithMany(p => p.Payments)
                .HasForeignKey(d => d.ApplicationId)
                .HasConstraintName("payment_application_id_fkey");
        });

        modelBuilder.Entity<Program>(entity =>
        {
            entity.HasKey(e => e.ProgramId).HasName("program_pkey");

            entity.ToTable("program");

            entity.Property(e => e.ProgramId).HasColumnName("program_id");
            entity.Property(e => e.CareerProspects).HasColumnName("career_prospects");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("timestamp without time zone")
                .HasColumnName("created_at");
            entity.Property(e => e.Description).HasColumnName("description");
            entity.Property(e => e.Duration)
                .HasMaxLength(100)
                .HasColumnName("duration");
            entity.Property(e => e.EnrollmentYearId).HasColumnName("enrollment_year_id");
            entity.Property(e => e.IsActive)
                .HasDefaultValue(true)
                .HasColumnName("is_active");
            entity.Property(e => e.MajorId).HasColumnName("major_id");
            entity.Property(e => e.ProgramName)
                .HasMaxLength(255)
                .HasColumnName("program_name");

            entity.HasOne(d => d.EnrollmentYear).WithMany(p => p.Programs)
                .HasForeignKey(d => d.EnrollmentYearId)
                .HasConstraintName("program_enrollment_year_id_fkey");

            entity.HasOne(d => d.Major).WithMany(p => p.Programs)
                .HasForeignKey(d => d.MajorId)
                .HasConstraintName("program_major_id_fkey");
        });

        modelBuilder.Entity<ProgramAdmissionConfig>(entity =>
        {
            entity.HasKey(e => e.ConfigId).HasName("program_admission_config_pkey");

            entity.ToTable("program_admission_config");

            entity.Property(e => e.ConfigId).HasColumnName("config_id");
            entity.Property(e => e.AdmissionTypeId).HasColumnName("admission_type_id");
            entity.Property(e => e.CampusId).HasColumnName("campus_id");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("timestamp without time zone")
                .HasColumnName("created_at");
            entity.Property(e => e.IsActive)
                .HasDefaultValue(true)
                .HasColumnName("is_active");
            entity.Property(e => e.ProgramId).HasColumnName("program_id");
            entity.Property(e => e.Quota).HasColumnName("quota");

            entity.HasOne(d => d.AdmissionType).WithMany(p => p.ProgramAdmissionConfigs)
                .HasForeignKey(d => d.AdmissionTypeId)
                .HasConstraintName("pac_admission_type_id_fkey");

            entity.HasOne(d => d.Campus).WithMany(p => p.ProgramAdmissionConfigs)
                .HasForeignKey(d => d.CampusId)
                .HasConstraintName("pac_campus_id_fkey");

            entity.HasOne(d => d.Program).WithMany(p => p.ProgramAdmissionConfigs)
                .HasForeignKey(d => d.ProgramId)
                .HasConstraintName("pac_program_id_fkey");
        });

        modelBuilder.Entity<Role>(entity =>
        {
            entity.HasKey(e => e.RoleId).HasName("role_pkey");

            entity.ToTable("role");

            entity.HasIndex(e => e.Name, "role_name_key").IsUnique();

            entity.Property(e => e.RoleId).HasColumnName("role_id");
            entity.Property(e => e.IsActive)
                .HasDefaultValue(true)
                .HasColumnName("is_active");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("name");
        });

        modelBuilder.Entity<User>(entity =>
        {
            entity.HasKey(e => e.UserId).HasName("user_pkey");

            entity.ToTable("user");

            entity.HasIndex(e => e.Email, "user_email_key").IsUnique();

            entity.HasIndex(e => e.Username, "user_username_key").IsUnique();

            entity.Property(e => e.UserId).HasColumnName("user_id");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("timestamp without time zone")
                .HasColumnName("created_at");
            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(150)
                .HasColumnName("email");
            entity.Property(e => e.IsActive)
                .HasDefaultValue(true)
                .HasColumnName("is_active");
            entity.Property(e => e.PasswordHash)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("password_hash");
            entity.Property(e => e.RoleId).HasColumnName("role_id");
            entity.Property(e => e.Username)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("username");

            entity.HasOne(d => d.Role).WithMany(p => p.Users)
                .HasForeignKey(d => d.RoleId)
                .HasConstraintName("user_role_id_fkey");
        });
        modelBuilder.HasSequence("program_admission_config_config_id_seq");
        modelBuilder.HasSequence<int>("seq_schema_version", "graphql").IsCyclic();

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}