// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MAEMS.Infrastructure.Models;

public partial class Program
{
    public int ProgramId { get; set; }

    public string ProgramName { get; set; }

    public int? MajorId { get; set; }

    public string Description { get; set; }

    public string CareerProspects { get; set; }

    public string Duration { get; set; }

    public bool? IsActive { get; set; }

    public DateTime? CreatedAt { get; set; }

    public int? EnrollmentYearId { get; set; }

    public virtual EnrollmentYear EnrollmentYear { get; set; }

    public virtual Major Major { get; set; }

    public virtual ICollection<ProgramAdmissionConfig> ProgramAdmissionConfigs { get; set; } = new List<ProgramAdmissionConfig>();
}