// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MAEMS.Infrastructure.Models;

public partial class ProgramAdmissionConfig
{
    public int ConfigId { get; set; }

    public int? ProgramId { get; set; }

    public int? CampusId { get; set; }

    public int? AdmissionTypeId { get; set; }

    public int? Quota { get; set; }

    public bool? IsActive { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual AdmissionType AdmissionType { get; set; }

    public virtual ICollection<Application> Applications { get; set; } = new List<Application>();

    public virtual Campus Campus { get; set; }

    public virtual Program Program { get; set; }
}